// Suggested training catalog, organized by the same categories used in
// Training.jsx. Leaders can pick from this list when logging a training, or
// just type a custom title instead — this is a convenience list, not a
// restriction (Training.jsx's category <select> already enforces valid values).
export const TRAINING_CATALOG = {
  Lean: [
    'Lean Manufacturing Fundamentals',
    '5S Workplace Organization',
    'Value Stream Mapping',
    'Kaizen Event Facilitation',
    'Kanban & Pull Systems',
    'Single-Minute Exchange of Die (SMED)',
    'Total Productive Maintenance (TPM)',
    'Standard Work Development',
    'Visual Management Principles',
    'Waste Identification (8 Wastes)',
    'Six Sigma Yellow Belt',
    'Six Sigma Green Belt',
  ],
  Leadership: [
    'Effective Coaching Skills',
    'Situational Leadership',
    'Leading Through Change',
    'Delegation & Accountability',
    'Giving & Receiving Feedback',
    'Conflict Resolution for Leaders',
    'Running Effective One-on-Ones',
    'Building High-Performing Teams',
    'Servant Leadership Fundamentals',
    'Performance Management Essentials',
    'Leading Remote & Hybrid Teams',
    'Succession Planning Basics',
    'Project Management Fundamentals',
    'Agile & Scrum Essentials',
  ],
  Safety: [
    'Safety & OSHA Compliance',
    'Hazard Communication (HazCom)',
    'Personal Protective Equipment (PPE)',
    'Lockout/Tagout (LOTO)',
    'Incident Investigation & Root Cause',
    'Ergonomics in the Workplace',
    'Forklift & Powered Equipment Safety',
    'Fire Safety & Emergency Response',
    'First Aid & CPR Certification',
    'Behavior-Based Safety Observation',
  ],
  'Soft Skills': [
    'Emotional Intelligence for Leaders',
    'DISC Personality Profiling',
    'Active Listening Techniques',
    'Time Management & Prioritization',
    'Public Speaking & Presentation Skills',
    'Cross-Cultural Communication',
    'Negotiation Fundamentals',
    'Stress Management & Resilience',
    'Written Business Communication',
    'Building Trust & Psychological Safety',
  ],
  Analytics: [
    'Data-Driven Decision Making',
    'Introduction to Excel for Business',
    'KPI & Metrics Design',
    'Statistical Process Control (SPC)',
    'Data Visualization Basics',
    'Root Cause Analysis with Data',
    'Forecasting & Trend Analysis',
    'Dashboard Reporting Fundamentals',
  ],
  Quality: [
    'Root Cause Analysis Techniques',
    'Quality Management Systems (ISO 9001 Overview)',
    'Statistical Sampling & Inspection',
    'Corrective & Preventive Action (CAPA)',
    'FMEA (Failure Mode & Effects Analysis)',
    'Control Plans & PPAP Basics',
    'Internal Auditing Fundamentals',
    'Supplier Quality Management',
  ],
};
